[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "helloworld_leorudczenko"
version = "0.0.1"
description = "A simple library to provide terminal output spacing"
readme = "README.md"
